log4j.rootLogger = info,D

# 根据文件大小的滚动ranger日志
log4j.appender.D = org.apache.log4j.RollingFileAppender
# 单个日志文件的最大大小
log4j.appender.D.MaxFileSize=200MB
# 保留的备份日志文件最大数量
log4j.appender.D.MaxBackupIndex=5

log4j.appender.D.File = /var/log/doris/fe/ranger.log
log4j.appender.D.Append = true
log4j.appender.D.Threshold = INFO
log4j.appender.D.layout = org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n
